FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY ./source/Backend/app /app
COPY ./source/Backend/requirements.txt /app/requirements.txt

ENV PYTHONPATH=/app

RUN python -m pip install pip --upgrade \
    && pip install -r requirements.txt

CMD [ "python", "app.py" ]
